// @generated by protobuf-ts 2.7.0 with parameter long_type_string
// @generated from protobuf file "proto/PerpetualGroupRefresh.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message PerpetualGroupRefresh
 */
export interface PerpetualGroupRefresh {
    /**
     * @generated from protobuf field: string uid = 1;
     */
    uid: string; // 用户uid
    /**
     * @generated from protobuf field: string groupId = 2;
     */
    groupId: string; // 合约组ID
    /**
     * @generated from protobuf field: string operate = 3;
     */
    operate: string; // update更新，delete 删除
    /**
     * @generated from protobuf field: string businessId = 4;
     */
    businessId: string; // 商户Id
}
// @generated message type with reflection information, may provide speed optimized methods
class PerpetualGroupRefresh$Type extends MessageType<PerpetualGroupRefresh> {
    constructor() {
        super("PerpetualGroupRefresh", [
            { no: 1, name: "uid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "groupId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "operate", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "businessId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PerpetualGroupRefresh>): PerpetualGroupRefresh {
        const message = { uid: "", groupId: "", operate: "", businessId: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PerpetualGroupRefresh>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PerpetualGroupRefresh): PerpetualGroupRefresh {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uid */ 1:
                    message.uid = reader.string();
                    break;
                case /* string groupId */ 2:
                    message.groupId = reader.string();
                    break;
                case /* string operate */ 3:
                    message.operate = reader.string();
                    break;
                case /* string businessId */ 4:
                    message.businessId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PerpetualGroupRefresh, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uid = 1; */
        if (message.uid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uid);
        /* string groupId = 2; */
        if (message.groupId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.groupId);
        /* string operate = 3; */
        if (message.operate !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.operate);
        /* string businessId = 4; */
        if (message.businessId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.businessId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PerpetualGroupRefresh
 */
export const PerpetualGroupRefresh = new PerpetualGroupRefresh$Type();
