// /** 融合模式定义黑名单 (先注释)* */
// export const FusionRouterApi = [
//   '/',
//   // 代理商
//   '/agent/apply',
//   '/agent/gains',
//   '/agent/gains/detail',
//   '/agent/invitation',
//   '/agent/invite-analytics/detail',
//   '/agent/invite-analytics/search',
//   '/agent/invite-analytics',
//   '/agent/join',
//   '/agent/manage',
//   '/agent/rank',
//   '/agent/result',
//   '/agent',
//   // 公告中心
//   '/announcement',
//   '/announcement/article',
//   '/assets/c2c',
//   // C2C
//   '/c2c/ads/history',
//   '/c2c/adv/details/',
//   '/c2c/center/account',
//   '/c2c/center/capital-transfer',
//   '/c2c/center/list-operation',
//   '/c2c/center/set-up',
//   '/c2c/center',
//   '/c2c/fast-trade',
//   '/c2c/merchant/application-success',
//   '/c2c/merchant/application',
//   '/c2c/merchant',
//   '/c2c/orders/appeal-upload',
//   '/c2c/orders/appeal',
//   '/c2c/orders/cancel',
//   '/c2c/orders/detail',
//   '/c2c/orders/im',
//   '/c2c/orders',
//   '/c2c/payments/collection-account',
//   '/c2c/payments/payment-details',
//   '/c2c/payments',
//   '/c2c/post/adv/result',
//   '/c2c/post/adv',
//   '/c2c/trade',
//   // 社群
//   '/community-groups',
//   // 下载
//   '/download',
//   // 帮助中心
//   '/support',
//   '/support/search',
//   '/support/navigation',
//   '/support/article',
//   // 站内信
//   '/inmail/all-reminder',
//   '/inmail/message-window',
//   '/inmail/push-settings',
//   '/inmail/reminder-page',
//   '/inmail',
//   // KYC
//   '/kyc/fail',
//   '/kyc/hold-up',
//   '/kyc/load-vip',
//   '/kyc/stand',
//   '/kyc/success',
//   '/kyc/up-load',
//   '/kyc',
//   // 登录
//   '/login',
//   // 个人中心
//   '/personal-center/about-us',
//   '/personal-center/account-security/anti-phishing',
//   '/personal-center/account-security/email/verification',
//   '/personal-center/account-security/email',
//   '/personal-center/account-security/google/verification',
//   '/personal-center/account-security/google',
//   '/personal-center/account-security/modify-password',
//   '/personal-center/account-security/phone/verification',
//   '/personal-center/account-security/phone',
//   '/personal-center/account-security/transaction-password',
//   '/personal-center/account-security',
//   '/personal-center/modify-username',
//   '/personal-center/network-check',
//   '/personal-center/settings/colors',
//   '/personal-center/settings/converted-currency',
//   '/personal-center/settings/language',
//   '/personal-center/settings/push-language',
//   '/personal-center/settings',
//   '/personal-center',
//   // 用户
//   '/register',
//   '/register/flow',
//   '/register/residence',
//   '/retrieve/reset-password',
//   '/retrieve',
//   '/safety-items/application-form',
//   '/safety-items',
//   '/safety-verification',
//   '/stay-tuned',
//   // 资产
//   '/assets/withdraw',
//   '/assets/recharge',
//   '/assets/withdraw/address/edit',
//   '/assets/withdraw/address/new',
//   '/assets/withdraw/address',
// ]

/** 融合模式定义白名单* */
export const FusionWhiteRouterApi = [
  // 资产
  '/assets',
  '/assets/coin-details',
  '/assets/financial-record/detail',
  '/assets/financial-record',
  '/assets/futures/details',
  '/assets/futures/history',
  '/assets/open/futures/account',
  // 合约
  '/futures',
  '/future/future-fundrecord-detail',
  '/future/groups',
  '/future/questionnaire',
  '/future/settings/additional-margin',
  '/future/settings/margin-coin',
  '/future/settings/margin/adjust-coin',
  '/future/settings/margin/auto-detail',
  '/future/settings/margin/records',
  '/future/settings/module-order',
  '/future/settings/order-confirm',
  '/future/settings/price-protect',
  '/future/settings/retrieval-method',
  '/future/settings/select-version',
  '/future/settings/settlement-currency',
  '/future/settings',
  '/future/stop-profitloss',
  '/futures/funding-history',
  '/futures/funding-history/quarterly',
  // 行情
  '/markets',
  '/market/activity',
  '/market/detail',
  '/market/futures/detail',
  '/markets/futures',
  '/markets/search',
  '/markets/sector-detail',
  '/markets/sector-table',
  '/markets/sector',
  '/markets/spot',
  '/my/futrue/detail',
  '/orders/future',
  '/orders/spot',
  '/trade',
  '/trade/settings/notification',
  // 个人设置
  '/personal-center/settings',
  '/personal-center/settings/language',
  '/personal-center/settings/colors',
]
